# Yaml file start

---

# create a script to config nginx in our web server

# who is the host - means name of the server 
- hosts: web
# gather data 
  gather_facts: yes
# we need admin access 
  become: true
# add the actual instructions 
  tasks:
   - name: Install/configure Nginx web server in web-VM
     apt: pkg=nginx state=present

# ensure ar=t the end of this script the status of nginx is running 




#- hosts: web



#  gather_facts: yes

#  become: true

#  tasks:

#    - name: Install Nginx in Web Server

#      apt: pkg=nginx state=present 

